//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public static class DelegateFactory
{
	public delegate Delegate DelegateValue(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateValue> dict = new Dictionary<Type, DelegateValue>();

	static DelegateFactory()
	{
		Register();
	}

	[NoToLuaAttribute]
	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), UnityEngine_Events_UnityAction);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(UnityEngine.UI.InputField.OnValidateInput), UnityEngine_UI_InputField_OnValidateInput);
		dict.Add(typeof(System.Action<NotiData>), System_Action_NotiData);
		dict.Add(typeof(System.Action<UnityEngine.Object[]>), System_Action_UnityEngine_Objects);
		dict.Add(typeof(KBEngine.NetworkInterface.ConnectCallback), KBEngine_NetworkInterface_ConnectCallback);
		dict.Add(typeof(EasyJoystick.JoystickMoveStartHandler), EasyJoystick_JoystickMoveStartHandler);
		dict.Add(typeof(EasyJoystick.JoystickMoveHandler), EasyJoystick_JoystickMoveHandler);
		dict.Add(typeof(EasyJoystick.JoystickMoveEndHandler), EasyJoystick_JoystickMoveEndHandler);
		dict.Add(typeof(EasyJoystick.JoystickTouchStartHandler), EasyJoystick_JoystickTouchStartHandler);
		dict.Add(typeof(EasyJoystick.JoystickTapHandler), EasyJoystick_JoystickTapHandler);
		dict.Add(typeof(EasyJoystick.JoystickDoubleTapHandler), EasyJoystick_JoystickDoubleTapHandler);
		dict.Add(typeof(EasyJoystick.JoystickTouchUpHandler), EasyJoystick_JoystickTouchUpHandler);
	}

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateValue Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func);
            
            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }  
            else
            {
                Delegate d = Create(func, null, false);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func);
                return d;
            }       
        }

        return Create(func, null, false);        
    }

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateValue Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func, self);

            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }
            else
            {
                Delegate d = Create(func, self, true);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func, self);
                return d;
            }
        }

        return Create(func, self, true);
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }

        LuaState state = remove.func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                state.DelayDispose(ld.self);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Event target = new System_Action_Event(func);
			System.Action d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Event target = new System_Action_Event(func, self);
			System.Action d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func);
			UnityEngine.Events.UnityAction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func, self);
			UnityEngine.Events.UnityAction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Camera_CameraCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate(UnityEngine.Camera param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func);
			UnityEngine.Camera.CameraCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func, self);
			UnityEngine.Camera.CameraCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LogCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LogCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate(string param0, string param1, UnityEngine.LogType param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func);
			UnityEngine.Application.LogCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func, self);
			UnityEngine.Application.LogCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate(float[] param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func);
			UnityEngine.AudioClip.PCMReaderCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func, self);
			UnityEngine.AudioClip.PCMReaderCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func, self);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate(UnityEngine.RectTransform param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func, self);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_UI_InputField_OnValidateInput_Event : LuaDelegate
	{
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func) : base(func) { }
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public char Call(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public char CallWithSelf(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UnityEngine_UI_InputField_OnValidateInput(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.UI.InputField.OnValidateInput fn = delegate(string param0, int param1, char param2) { return '\0'; };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func);
			UnityEngine.UI.InputField.OnValidateInput d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func, self);
			UnityEngine.UI.InputField.OnValidateInput d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_NotiData_Event : LuaDelegate
	{
		public System_Action_NotiData_Event(LuaFunction func) : base(func) { }
		public System_Action_NotiData_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(NotiData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(NotiData param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_NotiData(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<NotiData> fn = delegate(NotiData param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_NotiData_Event target = new System_Action_NotiData_Event(func);
			System.Action<NotiData> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_NotiData_Event target = new System_Action_NotiData_Event(func, self);
			System.Action<NotiData> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UnityEngine_Objects_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Objects_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Objects_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Object[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Object[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Objects(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Object[]> fn = delegate(UnityEngine.Object[] param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_Objects_Event target = new System_Action_UnityEngine_Objects_Event(func);
			System.Action<UnityEngine.Object[]> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_Objects_Event target = new System_Action_UnityEngine_Objects_Event(func, self);
			System.Action<UnityEngine.Object[]> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class KBEngine_NetworkInterface_ConnectCallback_Event : LuaDelegate
	{
		public KBEngine_NetworkInterface_ConnectCallback_Event(LuaFunction func) : base(func) { }
		public KBEngine_NetworkInterface_ConnectCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, int param1, bool param2, object param3)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, int param1, bool param2, object param3)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate KBEngine_NetworkInterface_ConnectCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			KBEngine.NetworkInterface.ConnectCallback fn = delegate(string param0, int param1, bool param2, object param3) { };
			return fn;
		}

		if(!flag)
		{
			KBEngine_NetworkInterface_ConnectCallback_Event target = new KBEngine_NetworkInterface_ConnectCallback_Event(func);
			KBEngine.NetworkInterface.ConnectCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			KBEngine_NetworkInterface_ConnectCallback_Event target = new KBEngine_NetworkInterface_ConnectCallback_Event(func, self);
			KBEngine.NetworkInterface.ConnectCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickMoveStartHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickMoveStartHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickMoveStartHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickMoveStartHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickMoveStartHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickMoveStartHandler_Event target = new EasyJoystick_JoystickMoveStartHandler_Event(func);
			EasyJoystick.JoystickMoveStartHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickMoveStartHandler_Event target = new EasyJoystick_JoystickMoveStartHandler_Event(func, self);
			EasyJoystick.JoystickMoveStartHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickMoveHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickMoveHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickMoveHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickMoveHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickMoveHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickMoveHandler_Event target = new EasyJoystick_JoystickMoveHandler_Event(func);
			EasyJoystick.JoystickMoveHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickMoveHandler_Event target = new EasyJoystick_JoystickMoveHandler_Event(func, self);
			EasyJoystick.JoystickMoveHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickMoveEndHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickMoveEndHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickMoveEndHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickMoveEndHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickMoveEndHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickMoveEndHandler_Event target = new EasyJoystick_JoystickMoveEndHandler_Event(func);
			EasyJoystick.JoystickMoveEndHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickMoveEndHandler_Event target = new EasyJoystick_JoystickMoveEndHandler_Event(func, self);
			EasyJoystick.JoystickMoveEndHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickTouchStartHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickTouchStartHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickTouchStartHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickTouchStartHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickTouchStartHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickTouchStartHandler_Event target = new EasyJoystick_JoystickTouchStartHandler_Event(func);
			EasyJoystick.JoystickTouchStartHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickTouchStartHandler_Event target = new EasyJoystick_JoystickTouchStartHandler_Event(func, self);
			EasyJoystick.JoystickTouchStartHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickTapHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickTapHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickTapHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickTapHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickTapHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickTapHandler_Event target = new EasyJoystick_JoystickTapHandler_Event(func);
			EasyJoystick.JoystickTapHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickTapHandler_Event target = new EasyJoystick_JoystickTapHandler_Event(func, self);
			EasyJoystick.JoystickTapHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickDoubleTapHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickDoubleTapHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickDoubleTapHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickDoubleTapHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickDoubleTapHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickDoubleTapHandler_Event target = new EasyJoystick_JoystickDoubleTapHandler_Event(func);
			EasyJoystick.JoystickDoubleTapHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickDoubleTapHandler_Event target = new EasyJoystick_JoystickDoubleTapHandler_Event(func, self);
			EasyJoystick.JoystickDoubleTapHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class EasyJoystick_JoystickTouchUpHandler_Event : LuaDelegate
	{
		public EasyJoystick_JoystickTouchUpHandler_Event(LuaFunction func) : base(func) { }
		public EasyJoystick_JoystickTouchUpHandler_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(MovingJoystick param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(MovingJoystick param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate EasyJoystick_JoystickTouchUpHandler(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			EasyJoystick.JoystickTouchUpHandler fn = delegate(MovingJoystick param0) { };
			return fn;
		}

		if(!flag)
		{
			EasyJoystick_JoystickTouchUpHandler_Event target = new EasyJoystick_JoystickTouchUpHandler_Event(func);
			EasyJoystick.JoystickTouchUpHandler d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			EasyJoystick_JoystickTouchUpHandler_Event target = new EasyJoystick_JoystickTouchUpHandler_Event(func, self);
			EasyJoystick.JoystickTouchUpHandler d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

}

