//this source code was auto-generated by tolua#, do not modify it
using System;
using UnityEngine;
using LuaInterface;

public static class LuaBinder
{
    public static void Bind(LuaState L)
    {
        throw new LuaException("Please generate LuaBinder files first!");
    }
}

